// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendars.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCalendar = `-- name: CreateCalendar :one
INSERT INTO calendars (
  title,
  description,
  password,
  salt,
  admin_token
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, admin_token
`

type CreateCalendarParams struct {
	Title       string  `json:"title"`
	Description *string `json:"description"`
	Password    *string `json:"password"`
	Salt        *string `json:"salt"`
	AdminToken  string  `json:"admin_token"`
}

type CreateCalendarRow struct {
	ID         pgtype.UUID `json:"id"`
	AdminToken string      `json:"admin_token"`
}

func (q *Queries) CreateCalendar(ctx context.Context, arg CreateCalendarParams) (CreateCalendarRow, error) {
	row := q.db.QueryRow(ctx, createCalendar,
		arg.Title,
		arg.Description,
		arg.Password,
		arg.Salt,
		arg.AdminToken,
	)
	var i CreateCalendarRow
	err := row.Scan(&i.ID, &i.AdminToken)
	return i, err
}

const deleteCalendarByIDAndAdminToken = `-- name: DeleteCalendarByIDAndAdminToken :exec
DELETE FROM calendars
WHERE id = $1 AND admin_token = $2
`

type DeleteCalendarByIDAndAdminTokenParams struct {
	ID         pgtype.UUID `json:"id"`
	AdminToken string      `json:"admin_token"`
}

func (q *Queries) DeleteCalendarByIDAndAdminToken(ctx context.Context, arg DeleteCalendarByIDAndAdminTokenParams) error {
	_, err := q.db.Exec(ctx, deleteCalendarByIDAndAdminToken, arg.ID, arg.AdminToken)
	return err
}

const getCalendarByID = `-- name: GetCalendarByID :one
SELECT 
  id, 
  title,
  description,
  created_at,
  updated_at
FROM calendars
WHERE id = $1
`

type GetCalendarByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCalendarByID(ctx context.Context, id pgtype.UUID) (GetCalendarByIDRow, error) {
	row := q.db.QueryRow(ctx, getCalendarByID, id)
	var i GetCalendarByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCalendarByIDAndAdminToken = `-- name: GetCalendarByIDAndAdminToken :one
SELECT 
  id, 
  title,
  description,
  created_at,
  updated_at
FROM calendars
WHERE id = $1 AND admin_token = $2
`

type GetCalendarByIDAndAdminTokenParams struct {
	ID         pgtype.UUID `json:"id"`
	AdminToken string      `json:"admin_token"`
}

type GetCalendarByIDAndAdminTokenRow struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCalendarByIDAndAdminToken(ctx context.Context, arg GetCalendarByIDAndAdminTokenParams) (GetCalendarByIDAndAdminTokenRow, error) {
	row := q.db.QueryRow(ctx, getCalendarByIDAndAdminToken, arg.ID, arg.AdminToken)
	var i GetCalendarByIDAndAdminTokenRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCalendarPasswordAndSaltByID = `-- name: GetCalendarPasswordAndSaltByID :one
SELECT 
  password,
  salt
FROM calendars
WHERE id = $1
`

type GetCalendarPasswordAndSaltByIDRow struct {
	Password *string `json:"password"`
	Salt     *string `json:"salt"`
}

func (q *Queries) GetCalendarPasswordAndSaltByID(ctx context.Context, id pgtype.UUID) (GetCalendarPasswordAndSaltByIDRow, error) {
	row := q.db.QueryRow(ctx, getCalendarPasswordAndSaltByID, id)
	var i GetCalendarPasswordAndSaltByIDRow
	err := row.Scan(&i.Password, &i.Salt)
	return i, err
}
