// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendars.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCalendar = `-- name: CreateCalendar :one
INSERT INTO calendars (id, title, description, dates)
VALUES ($1, $2, $3, $4)
RETURNING id, title, description, dates, created_at
`

type CreateCalendarParams struct {
	ID          string
	Title       string
	Description pgtype.Text
	Dates       []byte
}

func (q *Queries) CreateCalendar(ctx context.Context, arg CreateCalendarParams) (Calendar, error) {
	row := q.db.QueryRow(ctx, createCalendar,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Dates,
	)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Dates,
		&i.CreatedAt,
	)
	return i, err
}

const getCalendarByID = `-- name: GetCalendarByID :one
SELECT id, title, description, dates, created_at
FROM calendars
WHERE id = $1
`

func (q *Queries) GetCalendarByID(ctx context.Context, id string) (Calendar, error) {
	row := q.db.QueryRow(ctx, getCalendarByID, id)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Dates,
		&i.CreatedAt,
	)
	return i, err
}

const listCalendars = `-- name: ListCalendars :many
SELECT id, title, description, dates, created_at
FROM calendars
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCalendarsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListCalendars(ctx context.Context, arg ListCalendarsParams) ([]Calendar, error) {
	rows, err := q.db.Query(ctx, listCalendars, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Calendar
	for rows.Next() {
		var i Calendar
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Dates,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
