// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Calendar struct {
	ID          string
	Title       string
	Description pgtype.Text
	Dates       []byte
	CreatedAt   pgtype.Timestamptz
}

type Vote struct {
	ID         string
	CalendarID pgtype.Text
	Username   string
	Available  []byte
	CreatedAt  pgtype.Timestamptz
}
