// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCalendar(ctx context.Context, arg CreateCalendarParams) (CreateCalendarRow, error)
	CreateCalendarTimeSlot(ctx context.Context, arg CreateCalendarTimeSlotParams) (CalendarTimeSlot, error)
	CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error)
	DeleteCalendarByIDAndAdminToken(ctx context.Context, arg DeleteCalendarByIDAndAdminTokenParams) error
	DeleteCalendarTimeSlotByID(ctx context.Context, id pgtype.UUID) error
	DeleteVotesByID(ctx context.Context, id pgtype.UUID) error
	GetCalendarByID(ctx context.Context, id pgtype.UUID) (GetCalendarByIDRow, error)
	GetCalendarByIDAndAdminToken(ctx context.Context, arg GetCalendarByIDAndAdminTokenParams) (GetCalendarByIDAndAdminTokenRow, error)
	GetCalendarTimeSlotsByCalendarID(ctx context.Context, calendarID pgtype.UUID) ([]CalendarTimeSlot, error)
	ListVotesByCalendarID(ctx context.Context, calendarID pgtype.UUID) ([]ListVotesByCalendarIDRow, error)
}

var _ Querier = (*Queries)(nil)
