// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: votes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVote = `-- name: CreateVote :one
INSERT INTO votes (id, calendar_id, username, available)
VALUES ($1, $2, $3, $4)
RETURNING id, calendar_id, username, available, created_at
`

type CreateVoteParams struct {
	ID         string
	CalendarID pgtype.Text
	Username   string
	Available  []byte
}

func (q *Queries) CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error) {
	row := q.db.QueryRow(ctx, createVote,
		arg.ID,
		arg.CalendarID,
		arg.Username,
		arg.Available,
	)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.Username,
		&i.Available,
		&i.CreatedAt,
	)
	return i, err
}

const listVotesByCalendar = `-- name: ListVotesByCalendar :many
SELECT id, calendar_id, username, available, created_at
FROM votes
WHERE calendar_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListVotesByCalendar(ctx context.Context, calendarID pgtype.Text) ([]Vote, error) {
	rows, err := q.db.Query(ctx, listVotesByCalendar, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vote
	for rows.Next() {
		var i Vote
		if err := rows.Scan(
			&i.ID,
			&i.CalendarID,
			&i.Username,
			&i.Available,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
